### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Arthur-Milchior** [mjhea0/jquery-madlibs#2]
Hi,

First, thanks for this project. I discovered it thanks to http://www.pronouns.failedslacker.com/
Would you please accept to add a licence ? Since you seems to be the sole author, I assume it would not create any trouble legally. I would appreciate to reuse this code to translate http://www.pronouns.failedslacker.com into French, and to be sure I can legally do so.

Regards,
Arthur Milchior

**Comment by mjhea0** [comment]
I just added an MIT license. Cheers!
